api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
   # The title of the API.
    title: 'API Cours lior chamla'

    # The description of the API.
    description: 'API description'

    # The version of the API.
    version: '1.0.0'

    collection:
        pagination:
            enabled: false
            items_per_page: 5
            client_enabled: true
            client_items_per_page: true
            items_per_page_parameter_name: count
